development:
  adapter: postgresql
  encoding: unicode
  database: RecipeCapstone_development
  pool: 5
  host: localhost
  username: postgres
  password: Wa.ma.84

test:
  adapter: postgresql
  encoding: unicode
  database: RecipeCapstone_test
  pool: 5
  host: localhost
  username: postgres
  password: Wa.ma.84

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 